[package]
name = "cryptopals"
version = "0.1.0"
authors = ["Tiago MARTINEZ <tiago.martinez@ingenico.com>"]
edition = "2018"

[dependencies]
hex = "0.4"
base64 = "0.12.3"
rand = "0.7.3"
lazy_static = "1.4.0"
aes = "0.7.5"
